"""initial schema

Revision ID: 75776930b757
Revises: 
Create Date: 2026-08-31 21:51:15.369796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75776930b757'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE group_number_seq START WITH 100000 INCREMENT BY 1")
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.execute(
        "INSERT INTO system_config (key, value, description) VALUES "
        "('max_group_members', '200', '單一團人數上限硬上限'), "
        "('default_timezone', 'Asia/Taipei', '活動時間區間顯示基準時區') "
        "ON CONFLICT (key) DO NOTHING"
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_number', sa.BigInteger(), server_default=sa.text("nextval('group_number_seq')"), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password_ciphertext', postgresql.BYTEA(), nullable=True),
    sa.Column('password_nonce', postgresql.BYTEA(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('match_mode', sa.String(length=8), nullable=False),
    sa.Column('scheduling_mechanism', sa.String(length=16), nullable=False),
    sa.Column('activity_time_start', sa.Time(), nullable=True),
    sa.Column('activity_time_end', sa.Time(), nullable=True),
    sa.Column('current_member_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('admin_pin_hash', sa.String(length=255), nullable=False),
    sa.Column('admin_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('admin_locked_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('admin_token_version', sa.Integer(), nullable=False),
    sa.Column('base_settings_version', sa.Integer(), nullable=False),
    sa.Column('join_link_version', sa.Integer(), nullable=False),
    sa.Column('all_courts_link_version', sa.Integer(), nullable=False),
    sa.Column('join_link_token', sa.UUID(), nullable=False),
    sa.Column('all_courts_control_panel_token', sa.UUID(), nullable=False),
    sa.Column('scoring_mode', sa.String(length=8), nullable=False),
    sa.Column('target_score', sa.Integer(), nullable=False),
    sa.Column('deuce_threshold', sa.Integer(), nullable=False),
    sa.Column('cap_score', sa.Integer(), nullable=False),
    sa.Column('current_round_number', sa.Integer(), nullable=False),
    sa.Column('auto_next_round', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('all_courts_control_panel_token'),
    sa.UniqueConstraint('group_number'),
    sa.UniqueConstraint('join_link_token')
    )
    op.create_index(
        'ix_groups_status_last_activity', 'groups', ['status', 'last_activity_at']
    )
    op.create_index(
        'ix_groups_created_by',
        'groups',
        ['created_by_member_id'],
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table('courts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('wait_count', sa.Integer(), nullable=True),
    sa.Column('guest_session_token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_session_token')
    )
    op.create_index('ix_roster_group_status', 'roster_entries', ['group_id', 'status'])
    op.create_index(
        'ix_roster_member',
        'roster_entries',
        ['member_id'],
        postgresql_where=sa.text('member_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_entries')
    op.drop_table('courts')
    op.drop_table('groups')
    op.drop_table('system_config')
    op.drop_table('members')
    op.execute("DROP SEQUENCE IF EXISTS group_number_seq")
    # ### end Alembic commands ###
